spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/polestar-biz-sys${spring.datasource.mysql.url.suffix}
    username: root
    password: welcome
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    password:

mybatis-plus:
  type-aliases-package: com.github.panxiaole.**.model
  type-enums-package: com.github.panxiaole.**.enumeration
  mapper-locations:
    - classpath*:mybatis/mapper/*.xml
  configuration:
    jdbc-type-for-null: 'null'
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

swagger:
  basic:
    enable: false
    username: ${swagger.username}
    password: ${swagger.password}
  enable: true
  title: 系统管理
  description: 系统管理模块接口文档
  version: 1.0
  basePackage: com.github.panxiaole.polestar.biz.sys.controller
  termsOfServiceUrl: https://github.com/panxiaole/polestar
  contact:
    name: 潘小乐
    email: panxiaole@haier.com
    url: https://github.com/panxiaole

