server:
  port: 0

spring:
  # datasource
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/seed?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&autoReconnectForPools=true&serverTimezone=GMT%2B8
    username: root
    password: welcome
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    password:
  # spring boot admin ui
  boot:
    admin:
      client:
        url: ${adminui.hostname}
        username: ${adminui.username}
        password: ${adminui.password}
        instance:
          prefer-ip: true

# Eureka配置
eureka:
  instance:
    instance-id: ${spring.application.name}
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${eureka.server.zone}

# actuator监控
management:
  server:
    # actuator端口
    port: ${server.port}
  endpoints:
    web:
      #修改访问路径  2.0之前默认是/   2.0默认是 /actuator  可以通过这个属性值修改
      base-path: /actuator
      exposure:
        #开放所有页面节点  默认只开启了health、info两个节点
        include: '*'
  endpoint:
    health:
      #显示健康具体信息  默认不会显示详细信息
      show-details: always

# Mybatis-plus
mybatis-plus:
  type-aliases-package: com.haier.**.model
  type-enums-package: com.haier.**.enumeration
  mapper-locations:
    - classpath*:mybatis/mapper/*.xml
  configuration:
    jdbc-type-for-null: 'null'
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
