server:
  port: 0

spring:
  # datasource
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/seed?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&autoReconnectForPools=true&serverTimezone=GMT%2B8
    username: root
    password: welcome
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    password:
  # spring boot admin ui
  boot:
    admin:
      client:
        url: ${adminui.hostname}
        username: ${adminui.username}
        password: ${adminui.password}
        instance:
          prefer-ip: true

# Eureka\u914D\u7F6E
eureka:
  instance:
    instance-id: ${spring.application.name}
    #\u8BBF\u95EE\u8DEF\u5F84\u53EF\u4EE5\u663E\u793AIP\u5730\u5740
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${eureka.server.zone}

# actuator\u76D1\u63A7
management:
  server:
    #actuator\u7AEF\u53E3
    port: ${server.port}
  endpoints:
    web:
      #\u4FEE\u6539\u8BBF\u95EE\u8DEF\u5F84  2.0\u4E4B\u524D\u9ED8\u8BA4\u662F/   2.0\u9ED8\u8BA4\u662F /actuator  \u53EF\u4EE5\u901A\u8FC7\u8FD9\u4E2A\u5C5E\u6027\u503C\u4FEE\u6539
      base-path: /actuator
      exposure:
        #\u5F00\u653E\u6240\u6709\u9875\u9762\u8282\u70B9  \u9ED8\u8BA4\u53EA\u5F00\u542F\u4E86health\u3001info\u4E24\u4E2A\u8282\u70B9
        include: '*'
  endpoint:
    health:
      #\u663E\u793A\u5065\u5EB7\u5177\u4F53\u4FE1\u606F  \u9ED8\u8BA4\u4E0D\u4F1A\u663E\u793A\u8BE6\u7EC6\u4FE1\u606F
      show-details: always

# Mybatis-plus
mybatis-plus:
  type-aliases-package: com.haier.**.model
  type-enums-package: com.haier.**.enumeration
  mapper-locations:
    - classpath*:mybatis/mapper/*.xml
  configuration:
    jdbc-type-for-null: 'null'
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1 # \u903B\u8F91\u5DF2\u5220\u9664\u503C(\u9ED8\u8BA4\u4E3A 1)
      logic-not-delete-value: 0 # \u903B\u8F91\u672A\u5220\u9664\u503C(\u9ED8\u8BA4\u4E3A 0)
