# datasource
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/seed?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&autoReconnectForPools=true&serverTimezone=GMT%2B8
    username: root
    password: welcome
    driver-class-name: com.mysql.cj.jdbc.Driver
