server:
  port: ${springboot.admin.port}

spring:
  application:
    name: spring-boot-admin-server
  security:
    user:
      name: ${springboot.admin.username}
      password: ${springboot.admin.password}
